version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
      dev-tools:
        patterns:
          - "prettier*"
          - "husky"
          - "lint-staged"
